/**
 * Multi-Chat / Multi-Prompt Context Export Service for AURE Extension
 * Formats multiple prompt projects into cohesive AI handoff bundles (.txt & .md)
 * designed for seamless ingestion by ChatGPT, Claude, Gemini, Cursor, etc.
 *
 * Direct port of Prompt_Enhancer-FE multiChatExportService.ts
 */

export interface ExportDimension {
  id?: string;
  label: string;
  score?: number;
  desc?: string;
}

export interface ExportVersion {
  versionNumber: number;
  optimizedPrompt: string;
  overallScore?: number;
  tweakNote?: string;
  timestamp?: string | number;
  dimensions?: ExportDimension[];
}

export interface MultiChatExportItem {
  id: string;
  title?: string;
  originalPrompt: string;
  mode?: string;
  category?: string;
  targetModel?: string;
  score?: number;
  createdAt?: string | number;
  optimizedPrompt?: string;
  versions?: ExportVersion[];
}

export type ExportMode = 'smart' | 'transcript';
export type ExportFormat = 'txt' | 'md';

/**
 * Strips template variable declaration sections such as:
 * VARIABLES TO FILL (IF USER PROVIDES):
 * - {{USERSPECIFICCHARACTER_BACKSTORY}} → ...
 *
 * Preserves the actual prompt instructions, rules, and any following sections.
 */
export function stripVariablesSection(text: string): string {
  if (!text) return '';

  const pattern =
    /(?:(?:\r?\n){1,2}|^)[ \t]*(?:#{1,6}\s*|\*{1,2})?VARIABLES(?:\s+TO\s+FILL)?(?:\s*\([^)]*\))?:?(?:\*{1,2})?[ \t]*(?:\r?\n)(?:[ \t]+.*(?:\r?\n|$)|[ \t]*(?:[-*•]|\d+\.|{{|\[|`|\w+:).*(?:\r?\n|$)|[ \t]*(?:\r?\n|$))*(?=[ \t]*(?:#{1,6}\s+|[A-Z0-9 _-]{3,}:|\*{1,2}[A-Z0-9 _-]+:\*{1,2}|$))/gi;

  let cleaned = text.replace(pattern, '\n');

  // Also strip any trailing echoed raw input block at the very end of the prompt
  const trailingInputPattern =
    /(?:(?:\r?\n){1,2})[ \t]*(?:#{1,6}\s*|\*{1,2})?Input:(?:\*{1,2})?[ \t]*(?:\r?\n)[ \t]*[^\n]+[`'"\s]*$/i;
  cleaned = cleaned.replace(trailingInputPattern, '');

  return cleaned.trim();
}

/**
 * Builds a structured, high-signal AI Handoff Pack from multiple prompts.
 * Optimized to give a receiving AI (ChatGPT/Claude/Gemini/Cursor) complete
 * multi-project context without token-wasting transcript noise.
 */
export function buildMultiChatHandoff(
  items: MultiChatExportItem[],
  format: ExportFormat = 'txt'
): string {
  const isMd = format === 'md';
  const total = items.length;
  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  const sep = isMd ? '\n---\n' : '\n' + '='.repeat(80) + '\n';

  let doc = '';

  // Header & Master Primer
  if (isMd) {
    doc += `# 🧠 MULTI-PROJECT AI CONTEXT BUNDLE & CONTINUATION BRIEF\n\n`;
    doc += `> **Source**: Aure Prompt Intelligence Platform  \n`;
    doc += `> **Included Projects**: ${total}  \n`;
    doc += `> **Export Date**: ${dateStr}  \n\n`;

    doc += `## 📋 MASTER INSTRUCTION FOR RECEIVING AI\n\n`;
    doc += `You are receiving an aggregated multi-project context bundle containing **${total} distinct prompt project(s)**.\n\n`;
    doc += `**Your Objectives:**\n`;
    doc += `1. Ingest and retain the objectives, domain rules, constraints, and latest prompt states established for each project below.\n`;
    doc += `2. Keep each project's context cleanly partitioned in memory, but cross-reference knowledge when asked.\n`;
    doc += `3. When I refer to any project by title or number, immediately apply its established persona, constraints, and prompt style.\n\n`;
  } else {
    doc += `================================================================================\n`;
    doc += `          MULTI-PROJECT AI CONTEXT BUNDLE & CONTINUATION BRIEF\n`;
    doc += `================================================================================\n`;
    doc += `Generated by Aure Prompt Intelligence\n`;
    doc += `Total Included Projects: ${total}\n`;
    doc += `Export Date: ${dateStr}\n`;
    doc += `--------------------------------------------------------------------------------\n`;
    doc += `[MASTER INSTRUCTION FOR RECEIVING AI]\n`;
    doc += `--------------------------------------------------------------------------------\n`;
    doc += `You are receiving an aggregated multi-project context bundle containing ${total} distinct\n`;
    doc += `prompt project(s). Read the objectives, constraints, and current active prompt states\n`;
    doc += `for each project below.\n\n`;
    doc += `1. Ingest and retain the established goals, rules, and latest prompt states.\n`;
    doc += `2. Keep each project's context cleanly partitioned in memory, but cross-reference when asked.\n`;
    doc += `3. When I refer to any project by title or number, apply its established persona and style.\n`;
  }

  // Individual Project Modules
  items.forEach((item, index) => {
    const projNum = index + 1;
    const projectTitle = item.title || item.originalPrompt.slice(0, 60) || `Project ${projNum}`;

    let activePrompt = item.originalPrompt;
    let latestVersionNum = 1;
    const tweakNotes: string[] = [];
    const keyConstraints: string[] = [];

    if (item.versions && item.versions.length > 0) {
      const sorted = [...item.versions].sort((a, b) => a.versionNumber - b.versionNumber);
      const latest = sorted[sorted.length - 1];
      activePrompt = stripVariablesSection(latest.optimizedPrompt || item.originalPrompt);
      latestVersionNum = latest.versionNumber;

      sorted.forEach((v) => {
        if (v.tweakNote) {
          tweakNotes.push(`v${v.versionNumber}: ${v.tweakNote}`);
        }
      });

      if (latest.dimensions) {
        latest.dimensions.forEach((dim) => {
          if (dim.desc && dim.desc.length > 5) {
            keyConstraints.push(`${dim.label}: ${dim.desc}`);
          }
        });
      }
    } else if (item.optimizedPrompt) {
      activePrompt = stripVariablesSection(item.optimizedPrompt);
    }

    const allVersions =
      item.versions && item.versions.length > 0
        ? [...item.versions].sort((a, b) => a.versionNumber - b.versionNumber)
        : activePrompt && activePrompt.trim()
        ? [{ versionNumber: 1, optimizedPrompt: activePrompt }]
        : [];

    doc += sep;

    if (isMd) {
      doc += `### 📁 PROJECT ${projNum}: "${projectTitle}"\n\n`;

      doc += `#### 🎯 Original Intent / User Request\n`;
      doc += `> ${item.originalPrompt.replace(/\n/g, '\n> ')}\n\n`;

      if (keyConstraints.length > 0) {
        doc += `#### ⚖️ Established Constraints & Dimension Criteria\n`;
        keyConstraints.forEach((c) => {
          doc += `- **${c}**\n`;
        });
        doc += `\n`;
      }

      if (allVersions.length > 1) {
        doc += `#### 🚀 Enhanced Prompt Outputs (All ${allVersions.length} Versions)\n\n`;
        allVersions.forEach((v, idx) => {
          const isLatest = idx === allVersions.length - 1;
          const note = v.tweakNote ? ` (${v.tweakNote})` : '';
          const tag = isLatest ? ' ⭐ (Latest)' : '';
          const cleanPrompt = stripVariablesSection(v.optimizedPrompt || '');
          doc += `##### 🔹 Version ${v.versionNumber}${tag}${note}\n`;
          doc += `\`\`\`text\n${cleanPrompt}\n\`\`\`\n\n`;
        });
      } else if (allVersions.length === 1) {
        doc += `#### 🚀 Enhanced Prompt Output (Version 1 - Latest)\n`;
        const cleanPrompt = stripVariablesSection(allVersions[0].optimizedPrompt || '');
        doc += `\`\`\`text\n${cleanPrompt}\n\`\`\`\n\n`;
      } else {
        doc += `#### 🚀 Enhanced Prompt Output\n*(No enhanced prompt available)*\n\n`;
      }

      if (tweakNotes.length > 0) {
        doc += `#### 🔄 Iteration & Evolution Log\n`;
        tweakNotes.forEach((tn) => {
          doc += `- ${tn}\n`;
        });
        doc += `\n`;
      }
    } else {
      doc += `PROJECT ${projNum}: "${projectTitle}"\n`;
      doc += `--------------------------------------------------------------------------------\n`;
      doc += `[ORIGINAL INTENT / USER REQUEST]:\n`;
      doc += `  ${item.originalPrompt.replace(/\n/g, '\n  ')}\n\n`;

      if (keyConstraints.length > 0) {
        doc += `[ESTABLISHED CONSTRAINTS & CRITERIA]:\n`;
        keyConstraints.forEach((c) => {
          doc += `  • ${c}\n`;
        });
        doc += `\n`;
      }

      if (allVersions.length > 1) {
        doc += `[ENHANCED PROMPT OUTPUTS (ALL ${allVersions.length} VERSIONS)]:\n`;
        allVersions.forEach((v, idx) => {
          const isLatest = idx === allVersions.length - 1;
          const note = v.tweakNote ? ` [Note: ${v.tweakNote}]` : '';
          const tag = isLatest ? ' (LATEST)' : '';
          const cleanPrompt = stripVariablesSection(v.optimizedPrompt || '');
          doc += `--- Version ${v.versionNumber}${tag}${note} ---\n`;
          doc += `"""\n${cleanPrompt}\n"""\n\n`;
        });
      } else if (allVersions.length === 1) {
        doc += `[ENHANCED PROMPT OUTPUT (VERSION 1 - LATEST)]:\n`;
        const cleanPrompt = stripVariablesSection(allVersions[0].optimizedPrompt || '');
        doc += `"""\n${cleanPrompt}\n"""\n\n`;
      } else {
        doc += `[ENHANCED PROMPT OUTPUT]:\n*(No enhanced prompt available)*\n\n`;
      }

      if (tweakNotes.length > 0) {
        doc += `[ITERATION & EVOLUTION LOG]:\n`;
        tweakNotes.forEach((tn) => {
          doc += `  • ${tn}\n`;
        });
        doc += `\n`;
      }
    }
  });

  // Master Continuation Instruction
  doc += sep;
  if (isMd) {
    doc += `## 🤝 CONTINUATION INSTRUCTION FOR THE RECEIVING AI\n\n`;
    doc += `> *"Please confirm that you have ingested all ${total} project context(s) above. Provide a quick 1-sentence confirmation for each project, and ask me how we should proceed (e.g. continuing a specific project, synthesizing insights across them, or drafting next steps)."*\n`;
  } else {
    doc += `[CONTINUATION INSTRUCTION FOR THE RECEIVING AI]\n`;
    doc += `--------------------------------------------------------------------------------\n`;
    doc += `"Please confirm that you have ingested all ${total} project context(s) above.\n`;
    doc += `Provide a quick 1-sentence confirmation for each project, and ask me how we should\n`;
    doc += `proceed (e.g. continuing a specific project, synthesizing insights across them,\n`;
    doc += `or drafting next steps)."\n`;
    doc += `================================================================================\n`;
  }

  return doc;
}

/**
 * Builds a verbatim transcript of all selected prompts with full iteration history.
 */
export function buildMultiChatTranscript(
  items: MultiChatExportItem[],
  format: ExportFormat = 'txt'
): string {
  const isMd = format === 'md';
  const total = items.length;
  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  const sep = isMd ? '\n---\n' : '\n' + '='.repeat(80) + '\n';

  let doc = '';

  if (isMd) {
    doc += `# 📜 COMPLETE MULTI-SESSION AUDIT TRANSCRIPT\n\n`;
    doc += `> **Total Sessions**: ${total}  \n`;
    doc += `> **Export Date**: ${dateStr}  \n\n`;
  } else {
    doc += `================================================================================\n`;
    doc += `                    COMPLETE MULTI-SESSION AUDIT TRANSCRIPT\n`;
    doc += `================================================================================\n`;
    doc += `Total Sessions: ${total}\n`;
    doc += `Export Date: ${dateStr}\n\n`;
  }

  items.forEach((item, index) => {
    const projNum = index + 1;
    const title = item.title || item.originalPrompt.slice(0, 60) || `Session ${projNum}`;

    doc += sep;
    if (isMd) {
      doc += `## Session ${projNum}: ${title}\n\n`;
      doc += `### Original Input Prompt:\n\`\`\`text\n${item.originalPrompt}\n\`\`\`\n\n`;

      if (item.versions && item.versions.length > 0) {
        doc += `### Versions History:\n`;
        item.versions.forEach((v) => {
          doc += `#### Version ${v.versionNumber}\n`;
          if (v.tweakNote) doc += `*Tweak Note: ${v.tweakNote}*\n\n`;
          doc += `\`\`\`text\n${stripVariablesSection(v.optimizedPrompt || '')}\n\`\`\`\n\n`;
        });
      }
    } else {
      doc += `SESSION ${projNum}: ${title}\n`;
      doc += `--------------------------------------------------------------------------------\n`;
      doc += `[ORIGINAL PROMPT]:\n${item.originalPrompt}\n\n`;

      if (item.versions && item.versions.length > 0) {
        doc += `[VERSION HISTORY]:\n`;
        item.versions.forEach((v) => {
          doc += `--- Version ${v.versionNumber} ---\n`;
          if (v.tweakNote) doc += `Tweak: ${v.tweakNote}\n`;
          doc += `${stripVariablesSection(v.optimizedPrompt || '')}\n\n`;
        });
      }
    }
  });

  return doc;
}

/**
 * Downloads generated content as a file directly in browser or extension context.
 */
export function downloadTextFile(
  filename: string,
  content: string,
  mimeType = 'text/plain;charset=utf-8'
): void {
  try {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);

    // If chrome.downloads is available and supported
    if (typeof chrome !== 'undefined' && chrome.downloads?.download) {
      chrome.downloads.download({
        url,
        filename,
        saveAs: false,
      });
      return;
    }

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  } catch (err) {
    console.error('Failed to trigger file download:', err);
  }
}

/**
 * Copies string content to the system clipboard.
 */
export async function copyTextToClipboard(content: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(content);
      return true;
    }
    const textArea = document.createElement('textarea');
    textArea.value = content;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
    return false;
  }
}
